### PR TITLE
add dependencies loader-utils

### PR DESCRIPTION
**Pull request by homkai**
RT

### CODE REVIEW

**Comment by aganglada** [comment]
Cool! Thank you very much I will publish it, just now and let you know

**Comment by aganglada** [comment]
Do you mind fixing this related deprecation warning as well? https://github.com/webpack/loader-utils/issues/56

I will appreciate that 😃

**Comment by homkai** [comment]
const options = utils.parseQuery(this.query);
=>
const optionsConfig = this.options || this.query;
const options = typeof optionsConfig === 'object' ? utils.getOptions(optionsConfig) : utils.parseQuery(optionsConfig);

**Comment by aganglada** [comment]
Updated those changes in latest version (1.0.4)

**Pull request closed without merging**
