### PR TITLE
Add verbose option

### PR DESCRIPTION
**Pull request by mathiasscheffe**
* Have incorporated all changes discussed
* Have created a linter file to document the coding style and avoid confusion for the next person willing to contribute

### CODE REVIEW

**Review by aganglada — COMMENTED** [review]
Please rebase your branch from my branch. And please keep the PR simple. I wouldn't want to introduce `eslint` in this PR

**Comment by mathiasscheffe** [comment]
> Please rebase your branch from my branch. And please keep the PR simple. I wouldn't want to introduce `eslint` in this PR

All comments resolved.

**Review by aganglada — APPROVED** [review]
LGTM, thank you @mathiasscheffe

**Comment by aganglada** [comment]
@all-contributors please add @mathiasscheffe  for code

**Comment by aganglada** [comment]
@mathiasscheffe v1.0.5 has been published to https://www.npmjs.com/package/pattern-replace-loader

**Pull request merged**
